MvcWebApplication/Controllers/MenuListingsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MvcWebApplication.ViewModels.MenuListings;
using SharedLibrary.Common.Models;
using SharedLibrary.Enums;
using System.Threading.Tasks;
using System;
using MvcWebApplication.ViewFunctions;

namespace MvcWebApplication.Controllers
{
	public class MenuListingsController : Controller
	{
		private readonly ILogger<MenuListingsController> _logger;
		private readonly IMenuListingViewFunctions _menuListingViewFunctions;

		public MenuListingsController(ILogger<MenuListingsController> logger, IMenuListingViewFunctions menuListingViewFunctions)
		{
			_logger = logger;
			_menuListingViewFunctions = menuListingViewFunctions;
			_logger.LogDebug(1, "NLog injected into MenuListingsController");
		}

		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> Index()
		{
			_logger.LogInformation($"Index was called");
			var indexViewModel = new IndexViewModel();

			try
			{
				await _menuListingViewFunctions.ProcessIndexRequest(indexViewModel, HttpContext);
			}
			catch (Exception ex)
			{
				// Log the exception and return a friendly message back to the client
				_logger.LogError(ex, "Error occurred searching menu listings.");
				indexViewModel.Message = ex.Message;
			}

			return View(indexViewModel);
		}

		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> Search(MenuListingSearch menuListingSearch)
		{
			_logger.LogInformation($"Search was called with menuListingSearch: {menuListingSearch}");
			var searchViewModel = new SearchViewModel();
			searchViewModel.MenuListingSearch = menuListingSearch; ;

			try
			{
				await _menuListingViewFunctions.ProcessSearchRequest(searchViewModel, HttpContext);
			}
			catch (Exception ex)
			{
				// Log the exception and return a friendly message back to the client
				_logger.LogError(ex, "Error occurred searching menu listings.");
				searchViewModel.Message = ex.Message;
			}

			return View(searchViewModel);
		}
	}
}

MvcWebApplication/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MvcWebApplication.ViewFunctions;
using MvcWebApplication.ViewModels.Orders;
using SharedLibrary.Common.Models;
using SharedLibrary.Enums;
using System;
using System.Threading.Tasks;

namespace MvcWebApplication.Controllers
{

	public class OrdersController : Controller
	{
		private readonly ILogger<OrdersController> _logger;
		private readonly IOrdersViewFunctions _ordersViewFunctions;

		public OrdersController(ILogger<OrdersController> logger, IOrdersViewFunctions ordersViewFunctions)
		{
			_logger = logger;
			_ordersViewFunctions = ordersViewFunctions;
			_logger.LogDebug(1, "NLog injected into OrdersController");
		}

		[Authorize(Roles = "User")]
		public async Task<IActionResult> Index(OrderSearch orderSearch)
		{
			_logger.LogInformation($"Index was called with orderSearch: {orderSearch}");
			var IndexViewModel = new IndexViewModel();
			IndexViewModel.OrderSearch = orderSearch;

			try
			{
				await _ordersViewFunctions.GetOrders(IndexViewModel, HttpContext);
			}
			catch (Exception ex)
			{
				// Log the exception and return a friendly message back to the client
				_logger.LogError(ex, "Error occurred searching orders.");
				IndexViewModel.Message = ex.Message;
			}

			return View(IndexViewModel);
		}

		[Authorize(Roles = "User")]
		public async Task<IActionResult> CreateOrder(string userId)
		{
			_logger.LogInformation($"CreateOrder was called with userId: {userId}");


			try
			{
				// code goes here
				return View();
			}
			catch (Exception ex)
			{
				// Log the exception and return a friendly message back to the client
				_logger.LogError(ex, "Error occurred creating order from the shopping cart.");
				var indexViewModel = new IndexViewModel();
				indexViewModel.Message = ex.Message;
				return View("Index", indexViewModel);
			}
		}

		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> UserOrders(OrderSearch orderSearch)
		{
			_logger.LogInformation($"UserOrders was called with orderSearch: {orderSearch}");
			var userOrdersViewModel = new UserOrdersViewModel();
			userOrdersViewModel.OrderSearch = orderSearch;

			try
			{
				// code goes here
			}
			catch (Exception ex)
			{
				// Log the exception and return a friendly message back to the client
				_logger.LogError(ex, "Error occurred searching user orders.");
				userOrdersViewModel.Message = ex.Message;
			}

			return View(userOrdersViewModel);
		}

		[Authorize(Roles = "User, Admin")]
		public async Task<IActionResult> GetOrderDetails(string orderId, string userId, string searchSource)
		{
			_logger.LogInformation($"GetOrderDetails was called with orderId: {orderId} userId: {userId} searchSource: {searchSource}");
			var getOrderDetailsViewModel = new GetOrderDetailsViewModel();
			getOrderDetailsViewModel.SearchSource = searchSource;

			try
			{
				// need code here
			}
			catch (Exception ex)
			{
				// Log the exception and return a friendly message back to the client
				_logger.LogError(ex, "Error occurred getting order details.");
				getOrderDetailsViewModel.Message = ex.Message;
			}

			return View(getOrderDetailsViewModel);
		}
	}
}

MvcWebApplication/Controllers/ShoppingController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SharedLibrary.Enums;

namespace MvcWebApplication.Controllers
{

	public class ShoppingController : Controller
	{
		[Authorize(Roles = "User")]
		public IActionResult Index()
		{
			return View();
		}
	}
}

MvcWebApplication/Views/Shared/_Layout.cshtml
@using SharedLibrary.Enums
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - MvcWebApplication</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcWebApplication</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul id="userMenu" style="float:left" class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						@if (User.Identity.IsAuthenticated && (User.IsInRole(Roles.User.ToString())))
						{
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-controller="Shopping" asp-action="Index">Shop</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-controller="Orders" asp-action="Index">Orders</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark">View Cart</a>
							</li>
						}
					</ul>
					<ul id="adminMenu" style="float:right" class="navbar-nav flex-grow-1">
						@if (User.Identity.IsAuthenticated && (User.IsInRole(Roles.Admin.ToString())))
						{
							<li class="nav-item">
								<a class="nav-link text-dark" asp-controller="MenuListings" asp-action="Index">Menu Listing</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark">User Orders</a>
							</li>
						}
					</ul>
					@if (!User.Identity.IsAuthenticated)
					{
						<a asp-controller="Home" asp-action="Login">Login</a>
					}
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2022 - MvcWebApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
	<!-- In case any page needs to pull up a modal, it needs to be at a higher level than other elements -->
	<div id="modal-placeholder"></div>
</body>
</html>